[package]
name = "pomodoro"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
lazy_static = "1.4.0"
pulse = { package = "libpulse-binding" , version = "2.28.1" }
psimple = { package = "libpulse-simple-binding" , version = "2.28.1" }
notify-rust = "4.10.0"
ratatui = "0.25.0"
